/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 09-oct.-2022 02:20:38 a. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Coctel_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Coctel] DROP CONSTRAINT [FK_Coctel_Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_IngredienteCoctel_Unidad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [IngredienteCoctel] DROP CONSTRAINT [FK_IngredienteCoctel_Unidad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ingrediente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [IngredienteCoctel] DROP CONSTRAINT [FK_Ingrediente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Coctel]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [IngredienteCoctel] DROP CONSTRAINT [FK_Coctel]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Coctel]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Coctel]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Ingrediente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Ingrediente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[IngredienteCoctel]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [IngredienteCoctel]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Unidad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Unidad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

/* Create Tables */

CREATE TABLE [Coctel]
(
	[IdCoctel] int NOT NULL DEFAULT 1,
	[Nombre] varchar(50) NULL,
	[IdUsuario] int NOT NULL
)
GO

CREATE TABLE [Ingrediente]
(
	[IdIngrediente] int NOT NULL DEFAULT 1,
	[Nombre] varchar(50) NOT NULL,
)
GO

CREATE TABLE [IngredienteCoctel]
(
	[IdIngrediente] int NOT NULL,
	[IdCoctel] int NOT NULL,
	[CantidadUnidad] float NOT NULL,
	[IdUnidad] int NOT NULL
)
GO

CREATE TABLE [Unidad]
(
	[IdUnidad] int NOT NULL DEFAULT 1,
	[Nombre] varchar(20) NOT NULL,
	[Abreviatura] varchar(5) NOT NULL,
)
GO

CREATE TABLE [Usuario]
(
	[IdUsuario] int NOT NULL DEFAULT 1,
	[Username] varchar(50) NOT NULL,
	[Clave] varchar(200) NOT NULL,	-- This data will be encrypted using AES.
	[Correo] varchar(80) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Coctel] 
 ADD CONSTRAINT [PK_Coctel]
	PRIMARY KEY CLUSTERED ([IdCoctel] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Coctel_Usuario] 
 ON [Coctel] ([IdUsuario] ASC)
GO

ALTER TABLE [Ingrediente] 
 ADD CONSTRAINT [PK_Ingrediente]
	PRIMARY KEY CLUSTERED ([IdIngrediente] ASC)
GO

ALTER TABLE [IngredienteCoctel] 
 ADD CONSTRAINT [PK_IngredienteCoctel]
	PRIMARY KEY CLUSTERED ([IdIngrediente] ASC,[IdCoctel] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_IngredienteCoctel_Unidad] 
 ON [IngredienteCoctel] ([IdUnidad] ASC)
GO

ALTER TABLE [Unidad] 
 ADD CONSTRAINT [PK_Unidad]
	PRIMARY KEY CLUSTERED ([IdUnidad] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([IdUsuario] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Coctel] ADD CONSTRAINT [FK_Coctel_Usuario]
	FOREIGN KEY ([IdUsuario]) REFERENCES [Usuario] ([IdUsuario]) ON DELETE Cascade ON UPDATE No Action
GO

ALTER TABLE [IngredienteCoctel] ADD CONSTRAINT [FK_IngredienteCoctel_Unidad]
	FOREIGN KEY ([IdUnidad]) REFERENCES [Unidad] ([IdUnidad]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [IngredienteCoctel] ADD CONSTRAINT [FK_Ingrediente]
	FOREIGN KEY (IdIngrediente) REFERENCES  [Ingrediente] ([IdIngrediente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [IngredienteCoctel] ADD CONSTRAINT [FK_Ingrediente]
	FOREIGN KEY (IdCoctel) REFERENCES  [Coctel] ([IdCoctel]) ON DELETE No Action ON UPDATE No Action
GO


/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'This data will be encrypted using AES.', 'Schema', [dbo], 'table', [Usuario], 'column', [Clave]
GO

Insert into usuario values (1,'ADMIN','AerisVII7','hectoriinq@hotmail.com'); 
Insert into coctel values (1,'Coca de piña',1);
Insert into ingrediente values (1,'Coca');
Insert into unidad values (1,'Mililitros','ml');
Insert into IngredienteCoctel values (1,1,300,1);